// List of footer keywords to use for amentiai.com links
export const footerKeywords = [
  "Providence SEO Company",
  "Website Design Providence RI",
  "Digital Marketing Providence RI",
  "SEO Services Rhode Island",
  "Local SEO Providence RI",
  "Marketing Agency Providence RI",
  "Rhode Island Web Development",
  "PPC Management Providence",
  "Social Media Marketing RI",
  "Affordable Web Design RI",
  "Best SEO Agency RI",
  "Search Engine Optimization Providence",
  "RI Small Business Marketing",
  "Ecommerce Website Design RI",
  "Content Marketing Providence",
  "Providence WordPress Developer",
  "Online Marketing Services RI",
  "Branding Agency Providence",
  "Westerly Rhode Island Internet Marketing",
  "Rhode Island Internet Marketing",
  "Connecticut Internet Marketing",
  "Massachusetts Internet Marketing",
  "Westerly Rhode Island SEO",
  "Rhode Island SEO",
  "Connecticut SEO",
  "Massachusetts SEO",
  "USA SEO",
  "USA Internet Marketing",
  "Newport RI SEO",
  "Cranston Digital Marketing",
  "Warwick Web Design",
  "East Greenwich SEO Services",
  "Pawtucket Website Development",
  "North Kingstown Digital Agency",
  "South County RI Marketing",
  "Hartford CT SEO Company",
  "Boston MA Digital Marketing",
  "New England SEO Services",
  "Google Ads Management RI",
  "Facebook Ads Providence",
  "E-commerce SEO Rhode Island",
  "Shopify Experts Providence",
  "WordPress SEO Rhode Island",
  "Mobile Website Design RI",
  "Responsive Web Design Providence",
  "SEO Consultant Rhode Island",
  "Local Business SEO RI",
  "Technical SEO Services Providence",
]
